#!/bin/sh
echo Starting `date`

TEMPFILE=`mktemp -u`

uvccapture -v -o$TEMPFILE -x1280 -y720 -G48 -S10 -C20 -B10


echo "Converting to greyscale"

convert $TEMPFILE -gamma 1 -colorspace Gray capture.png

echo "Done `date`"
