#!/bin/sh
echo Starting `date`

TEMPFILE=`mktemp -u`

uvccapture -v -o$TEMPFILE -x1920 -y1080 -G10 -S10 -C10 -B10


echo "Converting to greyscale"

convert $TEMPFILE -colorspace Gray capture.png

echo "Done `date`"
